apiVersion: v1
kind: ReplicationController
metadata:
  name: myrelpication
  namespace: default
spec:
  replicas: 1
  selector:
    app: javapodapp #  for pod not mandatory
  template: # POD TEMPLATE
    metadata:
      name: mypodreplication #pod name
      labels:
       app: javapodapp
    spec:
      containers:
      - name: mypodreprication
        image: tomcat
        ports:
        - containerPort: 8080



---
apiVersion: v1
kind: Service
metadata:
 name: mysrvreplication
spec:
 type: NodePort
 selector:
  app: javapodapp
 ports:
 - port: 4040
   targetPort: 8080
